# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [13]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [1]:
a = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [3]:
print(len(a))

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [4]:
?np.zeros

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
a = np.zeros(10)
a[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
np.flip(a)

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
a = np.array([1,2,0,0,4,0])
for i in range(len(a)):
    if a[i] != 0:
        print(i)

0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [3]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
a = np.random.random((3,3,3))
a

array([[[0.4263227 , 0.86195112, 0.54457582],
        [0.73136707, 0.08784552, 0.15020981],
        [0.57550556, 0.5276254 , 0.19672962]],

       [[0.72643331, 0.38482539, 0.23604467],
        [0.42488953, 0.8628278 , 0.11407474],
        [0.1123034 , 0.20397508, 0.82638777]],

       [[0.63479169, 0.0283052 , 0.39139684],
        [0.20491118, 0.84444271, 0.87151163],
        [0.84346012, 0.47807333, 0.37676007]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [7]:
a = np.random.random((10,10))
print("Minimum and maximum values are {} and {} respectively".format(a.min(), a.max()))

Minimum and maximum values are 0.004293598019925127 and 0.9963682531583736 respectively


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [4]:
a = np.random.random(30)
mean_val = a.mean()
print(mean_val)

0.4661485366036053


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [187]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a) 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [59]:
a = np.arange(25).reshape(5,5)
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[ 0  0  0  0  0  0  0]
 [ 0  0  1  2  3  4  0]
 [ 0  5  6  7  8  9  0]
 [ 0 10 11 12 13 14  0]
 [ 0 15 16 17 18 19  0]
 [ 0 20 21 22 23 24  0]
 [ 0  0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [24]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [13]:
a = np.zeros((5,5))
for i in range(len(a)):
    j = 0
    while(j<4):
        a[j+1][j] = j+1
        j+=1
        
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [62]:
a = np.zeros((8,8))
for row_index, i in enumerate(a):
    for element_index, j in enumerate(i):
        if row_index%2 == 0 and element_index%2 == 0:
            j = 1
        elif row_index%2 != 0 and element_index%2 != 0:
            j = 1
            
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [60]:
a = np.zeros((8,8))
for index, i in enumerate(a):
    print(index, i)

0 [0. 0. 0. 0. 0. 0. 0. 0.]
1 [0. 0. 0. 0. 0. 0. 0. 0.]
2 [0. 0. 0. 0. 0. 0. 0. 0.]
3 [0. 0. 0. 0. 0. 0. 0. 0.]
4 [0. 0. 0. 0. 0. 0. 0. 0.]
5 [0. 0. 0. 0. 0. 0. 0. 0.]
6 [0. 0. 0. 0. 0. 0. 0. 0.]
7 [0. 0. 0. 0. 0. 0. 0. 0.]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [186]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [70]:
a = np.tile(np.array([[1,0],[0,1]]),(4,4))
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [15]:
a = np.random.random((5,5))

# Normalize the matrix by subtracting the mean and dividing by standard deviation
a = (a - a.mean()) / a.std()
print(a)

[[ 1.01941293  1.55381926 -0.13553881 -0.9997441  -0.79489757]
 [ 0.74058288 -1.0136027   0.25360216 -0.37586044  0.15980877]
 [-1.44401177 -1.02699419  0.2032612   0.13750522  1.35223223]
 [-1.39145344 -0.18491325 -1.37740276  1.06077585  1.6823498 ]
 [ 1.40578522  1.28889967 -0.97041505 -0.62321507 -0.51998605]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [113]:
color = np.dtype([("R", np.ubyte), ("G", np.ubyte), ("B", np.ubyte), ("A", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [17]:
a = np.random.random((5,3))
b = np.random.random((3,2))
print(a@b)

[[0.79366997 0.71779812]
 [0.29823812 0.1799413 ]
 [0.79959693 0.63968941]
 [0.89452497 0.75537777]
 [0.25032135 0.13333929]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [21]:
a = np.linspace(0, 20, 21)
a[(a>3) & (a<8)] *= -1
print(a)

[ 0.  1.  2.  3. -4. -5. -6. -7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [22]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [31]:
Z = np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)  # illegal

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_23988/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_23988/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [74]:
a = np.random.uniform(-5,10,15)
print(np.where(a>0, np.floor(a), np.ceil(a)))

[ 1.  5.  1. -3. -0.  9.  9.  5. -4.  5.  7. -2.  5. -0.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [33]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([2,4,6,8,10,13,14,15])

for i in a:
    for j in b:
        if i == j:
            print(i)

2
4
6
8


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [34]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [12]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_22067/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [185]:
today = np.datetime64("today", 'D')
yesterday = today - np.datetime64(1, 'D')
print(today)

2021-09-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [79]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [188]:
a = np.ones(3) * 1
b = np.ones(3) * 2
c = np.ones(3) * 3
np.add(a, b, out=b)
np.divide(a, 2, out=a)
np.negative(a, out=a)
np.multiply(a, b, out=a)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [196]:
a = np.random.uniform(0,20,10)

print(a.astype(int))
print(a - a%1)
print(a // 1)
print(np.floor(a))

[11  2 15  2  1  5  3 13 12  0]
[11.  2. 15.  2.  1.  5.  3. 13. 12.  0.]
[11.  2. 15.  2.  1.  5.  3. 13. 12.  0.]
[11.  2. 15.  2.  1.  5.  3. 13. 12.  0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [40]:
a = np.array([[i for i in range(0,5)] for j in range(0,5)])
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [78]:
def generate():
    a = np.array([])
    for i in range(10):
        a = np.append(a, i)
        
    return a
        
a = generate()
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [61]:
a = np.zeros(10)
for i in range(len(a)):
    a[i] = np.random.uniform(0,1)
    while(a[i] == 0):
        a[i] = np.random.uniform(0,1)
        
    
print(a)

[0.7091243  0.61730144 0.01926242 0.67642398 0.77939602 0.87589735
 0.23087755 0.83387841 0.32184543 0.63889443]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [37]:
a = np.random.random(20)
a.sort()
print(a)

[0.08503876 0.150688   0.18245629 0.2282944  0.26041189 0.30134723
 0.30700898 0.32959123 0.38298683 0.40245034 0.40314428 0.4327804
 0.56148327 0.58123379 0.60793363 0.61106492 0.742177   0.86406137
 0.93441837 0.93858956]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [48]:
a = np.linspace(1, 10, 10, dtype=int)
np.add.reduce(a)

55

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [40]:
A = np.random.random(10)
B = np.random.random(10)
print(np.array_equal(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [2]:
a = np.arange(20)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [46]:
a = np.random.random((10,2))

# Take the x's and y's separately into two arrays
X, Y = a[:,0], a[:,1]
r = np.sqrt(X**2 + Y**2)
phi = np.arctan(Y,X)

# Define empty array to store polar coordinates
b = np.zeros((10,2))
b[:,0] = r
b[:,1] = phi
print(b)

[[0.75245162 0.10216484]
 [0.55242982 0.24520565]
 [0.79596953 0.65925786]
 [1.12582141 0.70669448]
 [0.07495639 0.07337695]
 [0.82608546 0.33057434]
 [0.83688683 0.62414085]
 [0.82212902 0.68807891]
 [0.75552992 0.30404484]
 [1.16065674 0.66740936]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [53]:
a = np.random.random(10)
print(a)
a.max()
#print(np.where(a == a.max()))

[0.6991156  0.36796637 0.34263777 0.55134979 0.31916352 0.62129998
 0.93178065 0.77555659 0.64124029 0.17968419]


0.9317806514111272

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [184]:
a = np.zeros((5, 5), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [69]:
x = np.arange(1, 11, 1)
y = np.arange(11, 21, 1)

# Constructing the Cauchy matrix
c = np.zeros((len(x), len(x)))
for i in range(len(x)):
    for j in range(len(y)):
        c[i][j] = 1/(x[i] - y[j])
        
print(c)

[[-0.1        -0.09090909 -0.08333333 -0.07692308 -0.07142857 -0.06666667
  -0.0625     -0.05882353 -0.05555556 -0.05263158]
 [-0.11111111 -0.1        -0.09090909 -0.08333333 -0.07692308 -0.07142857
  -0.06666667 -0.0625     -0.05882353 -0.05555556]
 [-0.125      -0.11111111 -0.1        -0.09090909 -0.08333333 -0.07692308
  -0.07142857 -0.06666667 -0.0625     -0.05882353]
 [-0.14285714 -0.125      -0.11111111 -0.1        -0.09090909 -0.08333333
  -0.07692308 -0.07142857 -0.06666667 -0.0625    ]
 [-0.16666667 -0.14285714 -0.125      -0.11111111 -0.1        -0.09090909
  -0.08333333 -0.07692308 -0.07142857 -0.06666667]
 [-0.2        -0.16666667 -0.14285714 -0.125      -0.11111111 -0.1
  -0.09090909 -0.08333333 -0.07692308 -0.07142857]
 [-0.25       -0.2        -0.16666667 -0.14285714 -0.125      -0.11111111
  -0.1        -0.09090909 -0.08333333 -0.07692308]
 [-0.33333333 -0.25       -0.2        -0.16666667 -0.14285714 -0.125
  -0.11111111 -0.1        -0.09090909 -0.08333333]
 [-0.5      

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [117]:
for i in [np.int8, np.int32, np.int64]:
   print("Minimum integer for {} = {}".format(i, np.iinfo(i).min))
   print("Maximum integer for {} = {}".format(i, np.iinfo(i).max))
for i in [np.float32, np.float64]:
   print("Minimum float for {} = {}".format(i, np.finfo(i).min))
   print("Maximum float for {} = {}".format(i, np.finfo(i).max))

Minimum integer for <class 'numpy.int8'> = -128
Maximum integer for <class 'numpy.int8'> = 127
Minimum integer for <class 'numpy.int32'> = -2147483648
Maximum integer for <class 'numpy.int32'> = 2147483647
Minimum integer for <class 'numpy.int64'> = -9223372036854775808
Maximum integer for <class 'numpy.int64'> = 9223372036854775807
Minimum float for <class 'numpy.float32'> = -3.4028234663852886e+38
Maximum float for <class 'numpy.float32'> = 3.4028234663852886e+38
Minimum float for <class 'numpy.float64'> = -1.7976931348623157e+308
Maximum float for <class 'numpy.float64'> = 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [49]:
a = np.linspace(1, 10, 10, dtype=int)
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9
10


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [140]:
a = np.arange(100)
b = np.random.uniform(0,100)
index = (np.abs(a-b)).argmin()
print(a,b,a[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 76.1133584896479 76


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [141]:
a = np.zeros(10, [("position", [ ("x", float),
                                   ("y", float)]),
                    ("color",    [ ("r", float),
                                   ("g", float),
                                   ("b", float)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [84]:
a = np.random.random((100,2))
x, y = np.atleast_2d(a[:,0], a[:,1])
distance = np.sqrt((x - x.T)**2 + (y - y.T)**2)
print(distance)

[[0.         0.71455535 0.67712244 ... 0.60393929 0.50071663 0.12006455]
 [0.71455535 0.         0.08255242 ... 0.37345861 0.5503955  0.61692401]
 [0.67712244 0.08255242 0.         ... 0.4183002  0.47146601 0.5723247 ]
 ...
 [0.60393929 0.37345861 0.4183002  ... 0.         0.72654521 0.56216346]
 [0.50071663 0.5503955  0.47146601 ... 0.72654521 0.         0.38787496]
 [0.12006455 0.61692401 0.5723247  ... 0.56216346 0.38787496 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [127]:
a = 10*np.random.random((10,1)).astype(np.float32)
b = a.view(np.int32)
b[:] = a
print(b)

[[7]
 [6]
 [4]
 [3]
 [8]
 [9]
 [6]
 [1]
 [8]
 [7]]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [199]:
# Make a fake file and let numpy read it using `np.genfromtxt()`
from io import StringIO

file = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11''')
a = np.genfromtxt(file, delimiter=",", dtype=np.int)
print(a)


[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/tmp/ipykernel_17642/2850103809.py:9: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.genfromtxt(file, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [2]:
a = np.arange(25).reshape(5,5)
for index, value in np.ndenumerate(a):
    print("{}, {}".format(index, value))

(0, 0), 0
(0, 1), 1
(0, 2), 2
(0, 3), 3
(0, 4), 4
(1, 0), 5
(1, 1), 6
(1, 2), 7
(1, 3), 8
(1, 4), 9
(2, 0), 10
(2, 1), 11
(2, 2), 12
(2, 3), 13
(2, 4), 14
(3, 0), 15
(3, 1), 16
(3, 2), 17
(3, 3), 18
(3, 4), 19
(4, 0), 20
(4, 1), 21
(4, 2), 22
(4, 3), 23
(4, 4), 24


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [142]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
a = np.sqrt(x**2+y**2)
sigma, mu = 1.0, 0.0
g = np.exp(-((a-mu)**2 / (2.0 * sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [144]:
n, p = 10, 3
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),2)
print (a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [56]:
a = np.arange(25).reshape(5,5)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [145]:
a = np.random.randint(0,10,(3,3))
print("Original array = \n", a)
print("Sorted array = \n", a[a[:,1].argsort()])

Original array = 
 [[6 5 6]
 [4 7 3]
 [0 0 2]]
Sorted array = 
 [[0 0 2]
 [6 5 6]
 [4 7 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [109]:
a = np.random.randint(0,3,(4,10))
counter = 0
for i in (a.T):
    if i.any() == False:
        counter += 1
        
if counter == 0:
    print("True")
else:
    print("False")


True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [147]:
a = np.random.uniform(0,1,10)
z = 0.5
n = a.flat[np.abs(a - z).argmin()]
print(n)

0.5411542681473884


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [148]:
a = np.arange(3).reshape(1,3)
b = 3*np.random.randint(0,10,(3,1))

s = np.nditer([a,b,None])
for x,y,z in s: 
  z[...] = x + y
print(a,b,s.operands[2])

[[0 1 2]] [[12]
 [24]
 [ 3]] [[12 13 14]
 [24 25 26]
 [ 3  4  5]]


#### 63. Create an array class that has a name attribute (★★☆)

In [194]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:  return
        self.info = getattr(obj, 'name', "no name")

a = NamedArray(np.arange(10), "range_10")
print(a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [155]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

[2. 7. 3. 3. 2. 3. 2. 2. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [25]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,3,9,3,4,1])
c = np.bincount(a,weights=b)
print(c)

[0. 1. 3. 9. 3. 4. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [156]:
w,h = 16,16
a = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
b = a[...,0]*256*256 + a[...,1]*256 +a[...,2]
n = len(np.unique(b))
print(np.unique(a))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [157]:
a = np.random.randint(0,10,(3,4,3,4))
summmed = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(summmed)

[[45 35 68 71]
 [52 68 44 50]
 [45 44 52 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [158]:
a = np.random.uniform(0,1,100)
b = np.random.randint(0,10,100)
a_sums = np.bincount(b, weights=a)
a_counts = np.bincount(b)
a_means = a_sums / a_counts
print(a_means)

[0.37923179 0.48355827 0.49392154 0.30470768 0.4889281  0.57799042
 0.52360602 0.3122833  0.42979951 0.71896131]


#### 69. How to get the diagonal of a dot product? (★★★)

In [11]:
a = np.arange(25).reshape(5,5)
b = np.random.random(25).reshape(5,5)

print(np.diag(np.dot(a, b)))

[ 3.41698795 19.30676355 32.90754324 22.93867866 49.3555537 ]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [88]:
a = np.array([1,2,3,4,5])
b = np.zeros(len(a) + (len(a)-1)*3)
b[::4] = a  # Replace every 4th index with a value from array 'a'
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [50]:
a = np.arange(5*5*3).reshape(5,5,3)
b = 3*np.arange(5*5).reshape(5,5)
print(a * b[:,:,None])

[[[   0    0    0]
  [   9   12   15]
  [  36   42   48]
  [  81   90   99]
  [ 144  156  168]]

 [[ 225  240  255]
  [ 324  342  360]
  [ 441  462  483]
  [ 576  600  624]
  [ 729  756  783]]

 [[ 900  930  960]
  [1089 1122 1155]
  [1296 1332 1368]
  [1521 1560 1599]
  [1764 1806 1848]]

 [[2025 2070 2115]
  [2304 2352 2400]
  [2601 2652 2703]
  [2916 2970 3024]
  [3249 3306 3363]]

 [[3600 3660 3720]
  [3969 4032 4095]
  [4356 4422 4488]
  [4761 4830 4899]
  [5184 5256 5328]]]


#### 72. How to swap two rows of an array? (★★★)

In [42]:
a = np.arange(9).reshape(3,3)
a[[2,1]] = a[[1,2]]
print(a)

[[0 1 2]
 [6 7 8]
 [3 4 5]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [160]:
a0 = np.random.randint(0,100,(10,3))
a = np.roll(a0.repeat(2,axis=1),-1,axis=1)
a = a.reshape(len(a)*3,2)
a = np.sort(a,axis=1)
b = a.view(dtype=[('p0',a.dtype),('p1',a.dtype)])
b = np.unique(b)
print(b)

[( 0,  0) ( 0, 66) ( 0, 97) ( 0, 99) ( 1,  9) ( 1, 97) ( 4, 21) ( 4, 73)
 ( 9, 97) (10, 67) (10, 75) (21, 68) (21, 73) (21, 83) (32, 46) (32, 95)
 (46, 67) (46, 90) (46, 95) (50, 77) (50, 93) (65, 71) (65, 87) (67, 75)
 (67, 90) (68, 83) (71, 87) (77, 93) (97, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [15]:
C = np.bincount([2,2,2,8,8,4,4,10,10,10,10,3,5,7,7])
A = np.repeat(np.arange(len(C)), C)
print(A)

[ 2  2  2  3  4  4  5  7  7  8  8 10 10 10 10]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [161]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

a = np.arange(20)
print(moving_average(a, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [162]:
def builder(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

a = builder(np.arange(10), 3)
print(a)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [164]:
a = np.random.randint(0,2,100)
print("Original: \n", a)
print("Negating a boolean: ", np.logical_not(a, out=a))

a = np.random.uniform(-1.0,1.0,10)
print("Original: \n", a)
print("In place float sign change: \n", np.negative(a, out=a))

Original: 
 [0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 1 1 0 0 1 1 0 0 1 1 0 1 1 0 0 0 0 0 0 1
 0 0 0 1 1 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 1 0 1 1 1 0 0 1 1]
Negating a boolean:  [1 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 1 1 1 1 1 1 0
 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 0 1 0 0 0 1 1 0 0]
Original: 
 [-0.05673889  0.68755352 -0.49547103 -0.84228606  0.95272868  0.79932581
 -0.32362529 -0.51917581 -0.33039888 -0.70368662]
In place float sign change: 
 [ 0.05673889 -0.68755352  0.49547103  0.84228606 -0.95272868 -0.79932581
  0.32362529  0.51917581  0.33039888  0.70368662]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [165]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 0.62043281 10.78947784 10.19123307 10.32872788  1.77007171  2.49831405
  3.57297375  2.38871269  3.04826106 10.8564371 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [182]:
P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.53737144  8.45152633  8.13295551  2.60027479  1.91895477]
 [ 0.66170769  4.50943651  5.04126997  3.06609131 10.95982593]
 [10.50773106  2.07980718  1.1556407   8.21115121  0.78836205]
 [ 2.90586657  3.58044231  4.29205122  0.61079002  8.14008728]
 [ 3.75537617  2.27908039  2.9834588   1.41753549  7.07442685]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [132]:
a = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 0 0 1 0 2 0 0 2 2]
 [0 0 1 2 0 0 2 0 1 1]
 [1 0 1 0 0 0 2 2 0 0]]
[[0 0 0 0 0]
 [0 2 0 0 1]
 [0 0 0 1 2]
 [0 1 0 1 0]
 [0 0 0 0 0]]


/tmp/ipykernel_17642/3571009467.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [134]:
a = np.arange(1,15,dtype=int)

def generate(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

R = generate(a, 4)
print("Original array: \n", a)
print("After strides: \n", R)
print(R)

Original array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After strides: 
 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [10]:
from numpy.linalg import matrix_rank
a = np.arange(9).reshape(3,3)
print(matrix_rank(a))

2


#### 83. How to find the most frequent value in an array?

In [17]:
a = np.bincount([1,2,3,4,4,4])
print(np.argmax(a))

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [135]:
a = np.random.randint(0,5,(6,6))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
b = np.lib.stride_tricks.as_strided(a, shape=(i, j, n, n), strides=a.strides + a.strides)
print(b)

[[[[2 2 1]
   [1 2 0]
   [1 4 3]]

  [[2 1 0]
   [2 0 4]
   [4 3 0]]

  [[1 0 0]
   [0 4 2]
   [3 0 1]]

  [[0 0 0]
   [4 2 3]
   [0 1 3]]

  [[0 0 1]
   [2 3 1]
   [1 3 1]]

  [[0 1 2]
   [3 1 4]
   [3 1 3]]

  [[1 2 0]
   [1 4 3]
   [1 3 0]]

  [[2 0 4]
   [4 3 0]
   [3 0 2]]]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [136]:
class Symmetric(np.ndarray):
    def __setitem__(self, index, value):
      i,j=index
      super(Symmetric, self).__setitem__((i,j), value)
      super(Symmetric, self).__setitem__((j,i), value)

def symmetric(a):
    return np.asarray(a + a.T - np.diag(a.diagonal())).view(Symmetric)

a = symmetric(np.random.randint(0,10,(5,5)))
a[2,3] = 42
print(a)

[[ 6 10 11 12  0]
 [10  1  8  5  8]
 [11  8  7 42 14]
 [12  5 42  6  6]
 [ 0  8 14  6  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [138]:
p, n = 10, 20
a = np.ones((p,n,n))
b = np.ones((p,n,1))
c = np.tensordot(a, b, axes=[[0, 2], [0, 1]])
print(c)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [139]:
a = np.ones((16,16))
k = 4
s = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], k), axis=0),
                                       np.arange(0, a.shape[1], k), axis=1)
print("Input array: \n", a)
print("Block sum: \n", s)

Input array: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Block sum: 
 [[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [181]:
def gof(a):
    # Count neighbours
    N = (a[0:-2,0:-2] + a[0:-2,1:-1] + a[0:-2,2:] +
         a[1:-1,0:-2]                + a[1:-1,2:] +
         a[2:  ,0:-2] + a[2:  ,1:-1] + a[2:  ,2:])

    # Apply rules
    birth = (N==3) & (a[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (a[1:-1,1:-1]==1)
    a[...] = 0
    a[1:-1,1:-1][birth | survive] = 1
    return a

a = np.random.randint(0,2,(50,50))
for i in range(100): 
    a = gof(a)
    
print(a)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [177]:
a = np.arange(10000)
np.random.shuffle(a)
n = 5

print(a[np.argsort(a)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [176]:
def cartesian(mult_arrays):
    mult_arrays = [np.asarray(a) for a in mult_arrays]
    shape = (len(x) for x in mult_arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(mult_arrays), -1).T

    for n, arr in enumerate(mult_arrays):
        ix[:, n] = mult_arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [175]:
a = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
b = np.core.records.fromarrays(a.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(b)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [174]:
x = np.random.rand(5*10^7)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.34 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.17 µs ± 26.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
3.08 µs ± 15.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [173]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))

c = (a[..., np.newaxis, np.newaxis] == b)
rows = (c.sum(axis=(1,2,3)) >= b.shape[1]).nonzero()[0]
print(rows)

[0 1 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [172]:
a = np.random.randint(0,5,(10,3))
b = np.logical_and.reduce(a[:,1:] == a[:,:-1], axis=1)
c = a[~b]
print(a)
print(c)

[[0 3 1]
 [3 4 3]
 [0 4 1]
 [1 1 0]
 [4 4 2]
 [2 4 3]
 [0 2 1]
 [0 2 2]
 [2 3 3]
 [4 2 1]]
[[0 3 1]
 [3 4 3]
 [0 4 1]
 [1 1 0]
 [4 4 2]
 [2 4 3]
 [0 2 1]
 [0 2 2]
 [2 3 3]
 [4 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [171]:
a = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
b = ((a.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(b[:,::-1])

a = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(a[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [41]:
a = np.arange(25).reshape(5,5)
b = np.array([np.random.randint(25) for i in range(25)]).reshape(5,5)

for i in a:
    for j in b:
        if i.all() != j.all():
            print(i, j)


[0 1 2 3 4] [16 24 17 18  9]
[0 1 2 3 4] [13 24 14  5  3]
[0 1 2 3 4] [ 9 13 20  6 12]
[0 1 2 3 4] [ 1 15 22 12  5]
[5 6 7 8 9] [ 8 24 24  0 18]
[10 11 12 13 14] [ 8 24 24  0 18]
[15 16 17 18 19] [ 8 24 24  0 18]
[20 21 22 23 24] [ 8 24 24  0 18]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [111]:
A = np.arange(10)
B = np.linspace(0, 20, 10)
print("Inner: {}".format(np.einsum('i,i', A, B)))
print("Outer: {}".format(np.einsum('i,j->ij', A, B)))
print("Sum of A: {}".format(np.einsum('i->', A)))
print("Product: {}".format(np.einsum('i,i->i', A, B)))

Inner: 633.3333333333334
Outer: [[  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           2.22222222   4.44444444   6.66666667   8.88888889
   11.11111111  13.33333333  15.55555556  17.77777778  20.        ]
 [  0.           4.44444444   8.88888889  13.33333333  17.77777778
   22.22222222  26.66666667  31.11111111  35.55555556  40.        ]
 [  0.           6.66666667  13.33333333  20.          26.66666667
   33.33333333  40.          46.66666667  53.33333333  60.        ]
 [  0.           8.88888889  17.77777778  26.66666667  35.55555556
   44.44444444  53.33333333  62.22222222  71.11111111  80.        ]
 [  0.          11.11111111  22.22222222  33.33333333  44.44444444
   55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
 [  0.          13.33333333  26.66666667  40.          53.33333333
   66.66666667  80.          93.33333333 106.66666667 120.        ]
 [  0.          15.55555556  31

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [170]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5  # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)
print(r_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [168]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],[2.0, 0.0, 1.0, 1.0],[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [169]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
conf_interval = np.percentile(means, [2.5, 97.5])
print(conf_interval)

[-0.1066307   0.29291231]
